### PR TITLE
chore(parser): add --subservices tag

### PR DESCRIPTION
**Pull request by pedrooot**
### Context

Prowler allows to execute checks from a specific service using --service / --services tag

### Description

This pr adds the --subservice / --subservices tag in Prowler. This feature allows you to run checks for a specific subservice(s)

### License

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Comment by MrCloudSec** [comment]
Good job @pedrooot ! But we will have to check all the subservices within the check's metadata. For example, in Kubernetes there are no subservices.

**Comment by MrCloudSec** [comment]
And we need to differentiate the service for each subservice.

**Comment by jfagoagas** [comment]
Are we going to allow the use of `--service` and `--subservice` in the same execution? I think it's important just to check an specific subservice instead of all.

**Comment by jfagoagas** [comment]
We are closing this issue. We are not sure about the `subservice` concept since it was crafted by us and maybe it should be replaced by the `ResourceType`. We will circle around this again in the future.

Thanks for your effort @pedrooot 👏

**Pull request closed without merging**
