### PR TITLE
Checks/find security groups with wide open non rfc1918 IPv4 addresses

### PR DESCRIPTION
**Pull request by renuez**
By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

This is another check to raise attention to security groups that are potentially much opened to public IPv4 addresses (non RFC1918). 

Currently the default is >/24, but I'm open for a discussion and your experiences to find a better default.

### CODE REVIEW

**Review by toniblyx — CHANGES_REQUESTED** [review]
Same as in other checks, each `aws` command requires the variable `$PROFILE_OPT` that includes options if different profile is loaded.

**Comment by renuez** [comment]
@toniblyx please leave that PR a week with me for additional testing.

**Review by toniblyx — APPROVED** [review]
LGTM

**Comment by toniblyx** [comment]
Thanks!

**Pull request merged**
