### PR TITLE
Fix LICENSE

### PR DESCRIPTION
**Pull request by jphuynh**
Signed-off-by: Jean-Pierre Huynh <jean-pierre.huynh@ounet.fr>

### CODE REVIEW

**Comment by toniblyx** [comment]
Prowler is Apache 2.0 licensed, and it is specified at github repo level since first day. I don't actually understand this PR, it might be a mistake.

**Comment by jphuynh** [comment]
You might want to update the header in the `prowler` script then because it says:

```
# This work is licensed under a Creative Commons Attribution-NonCommercial-ShareAlike 4.0
# International Public License. The link to the license terms can be found at
# https://creativecommons.org/licenses/by-nc-sa/4.0/legalcode
#
# Author: Toni de la Fuente - @ToniBlyx / Alfresco Software Inc.
```

**Comment by jphuynh** [comment]
I assumed that `CC BY-NC-SA 4.0` was the desired license since it was declared in the main file.

**Comment by toniblyx** [comment]
ah ok ok, sorry @jphuynh, my bad, I didn't remember that. I added that license in the prowler file because it is the CIS benchmark guides license. I didn't change it when I created this Github repo. So this PR is correct. Thanks!

**Pull request merged**
