### PR TITLE
fix(cloudfront): Bad https_enabled check comparison

### LINKED ISSUE #2425: [Bug]: cloudfront_distributions_https_enabled false positive
### Steps to Reproduce

Prowler reports cloudfront_distributions_https_enabled as failed when the cloudfront distribution has "Redirect HTTP to HTTPS"  set in viewer protocol policy on behavior.

### Expected behavior

For the example attached, it should "PASS".

### Actual Result with Screenshots or Logs

```
{
    "ETag": "XXXXXXXX",
    "DistributionConfig": {
        "CallerReference": "1561029664879",
        "Aliases": {
            "Quantity": 1,
            "Items": [
                xxxxxxxxx"
            ]
        },
        "DefaultRootObject": "",
        "Origins": {
            "Quantity": 1,
            "Items": [
                {
                    "Id": "xxxxxxxx",
                    "DomainName": "xxxxxxxx",
                    "OriginPath": "",
                    "CustomHeaders": {
                        "Quantity": 0
                    },
                    "S3OriginConfig": {
                        "OriginAccessIdentity": ""
                    },
                    "ConnectionAttempts": 3,
                    "ConnectionTimeout": 10,
                    "OriginShield": {
                        "Enabled": false
                    },
                    "OriginAccessControlId": ""
                }
            ]
        },
        "OriginGroups": {
            "Quantity": 0
        },
        "DefaultCacheBehavior": {
            "TargetOriginId": "xxxxxxxx",
            "TrustedSigners": {
                "Enabled": false,
                "Quantity": 0
            },
            "TrustedKeyGroups": {
                "Enabled": false,
                "Quantity": 0
            },
            "ViewerProtocolPolicy": "redirect-to-https",
            "AllowedMethods": {
                "Quantity": 2,
                "Items": [
                    "HEAD",
                    "GET"
                ],
                "CachedMethods": {
                    "Quantity": 2,
                    "Items": [
                        "HEAD",
                        "GET"
                    ]
                }
            },
            "SmoothStreaming": false,
            "Compress": true,
            "LambdaFunctionAssociations": {
                "Quantity": 0
            },
            "FunctionAssociations": {
                "Quantity": 0
            },
            "FieldLevelEncryptionId": "",
            "ResponseHeadersPolicyId": "4dde66c4-bea6-48eb-9d5c-520b29617292",
            "ForwardedValues": {
                "QueryString": true,
                "Cookies": {
                    "Forward": "none"
                },
                "Headers": {
                    "Quantity": 2,
                    "Items": [
                        "Origin",
                        "Referer"
                    ]
                },
                "QueryStringCacheKeys": {
                    "Quantity": 0
                }
            },
            "MinTTL": 0,
            "DefaultTTL": 86400,
            "MaxTTL": 31536000
        },
        "CacheBehaviors": {
            "Quantity": 0
        },
        "CustomErrorResponses": {
            "Quantity": 0
        },
        "Comment": "xxxxxxx",
        "Logging": {
            "Enabled": true,
            "IncludeCookies": false,
            "Bucket": "xxxxxxx",
            "Prefix": "xxxxxxx"
        },
        "PriceClass": "PriceClass_100",
        "Enabled": true,
        "ViewerCertificate": {
            "CloudFrontDefaultCertificate": false,
            "ACMCertificateArn": "xxxxxxxx",
            "SSLSupportMethod": "sni-only",
            "MinimumProtocolVersion": "TLSv1.2_2021",
            "Certificate": "xxxxxxxxxxxxx",
            "CertificateSource": "acm"
        },
        "Restrictions": {
            "GeoRestriction": {
                "RestrictionType": "none",
                "Quantity": 0
            }
        },
        "WebACLId": "",
        "HttpVersion": "http2and3",
        "IsIPV6Enabled": true,
        "ContinuousDeploymentPolicyId": "",
        "Staging": false
    }
}
```

### How did you install Prowler?

Docker (docker pull toniblyx/prowler)

### Environment Resource

7. Workstation

### OS used

5. Docker

### Prowler version

3.5.3

### Pip version

From official docker image

### Context

_No response_

### PR DESCRIPTION
**Pull request by christiandavilakoobin**
### Context

Cloudfront https check fails because was unable to detect correctly the viewer protocol policy from cloudfront distribution

Fixes #2425 

### Description

Fixed the protocol policy enum comparation

### License

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Comment by sergargar** [comment]
Hi @christiandavilakoobin, does this PR solve https://github.com/prowler-cloud/prowler/issues/2425?

**Comment by christiandavilakoobin** [comment]
Hi Sergio,

Yes, it does.

Enviado desde Outlook para iOS<https://aka.ms/o0ukef>
________________________________
De: Sergio Garcia ***@***.***>
Enviado: Thursday, June 1, 2023 6:35:21 PM
Para: prowler-cloud/prowler ***@***.***>
Cc: Christian Dávila ***@***.***>; Mention ***@***.***>
Asunto: Re: [prowler-cloud/prowler] fix(cloudfront): Bad https_enabled check comparasion (PR #2430)


Hi @christiandavilakoobin<https://github.com/christiandavilakoobin>, does this PR solve #2425<https://github.com/prowler-cloud/prowler/issues/2425>?

**Review by jfagoagas — DISMISSED** [review]
Awesome @christiandavilakoobin, really good catch!!

Thanks for using Prowler 🚀

**Comment by jfagoagas** [comment]
Hi @christiandavilakoobin, I had to make two adjustments in the check to fix some tests. Could you please execute Prowler using the latest PR commit? If everything works great we can merge it!

**Review by jfagoagas — DISMISSED** [review]

**Comment by christiandavilakoobin** [comment]
Hi @jfagoagas,

With your adjustments it seems to PASS always. I've some Cloudfront distributions accepting HTTP and it doesn't detect them.

**Comment by christiandavilakoobin** [comment]
Sorry, it didn't PASS, but it seems to skip this test. I have 30 cloudfront resources to check, and with your adjustements it found 120 findings instead 150, and the protocol checks doesn't appear on the result.

**Comment by jfagoagas** [comment]
That is weird, I'll check it back later and let you know.

Thanks for testing it.

**Comment by jfagoagas** [comment]
Could you please include the following `print(distribution.default_cache_config.viewer_protocol_policy)` at line 20 in `prowler/providers/aws/services/cloudfront/cloudfront_distributions_https_enabled/cloudfront_distributions_https_enabled.py` and paste the output here?

Thanks!

**Comment by christiandavilakoobin** [comment]
Hi @jfagoagas,

I'm not sure if you still need the print, but this what is shows the command `print(distribution.default_cache_config.viewer_protocol_policy)`:

redirect-to-https
redirect-to-https
redirect-to-https
redirect-to-https
redirect-to-https
redirect-to-https
redirect-to-https
redirect-to-https
redirect-to-https
redirect-to-https
redirect-to-https
redirect-to-https
redirect-to-https
redirect-to-https
redirect-to-https
redirect-to-https
redirect-to-https
redirect-to-https
redirect-to-https
allow-all
allow-all
allow-all
allow-all
allow-all
redirect-to-https
allow-all
allow-all
redirect-to-https
redirect-to-https
redirect-to-https

**Comment by jfagoagas** [comment]
Hi @christiandavilakoobin, could you please test the latest commit? I've encountered a bug in the CloudFront's classes and it seems not to be related with the check but the class that stores the cache config.

Thanks!

**Comment by christiandavilakoobin** [comment]
Hi @jfagoagas!

It seems to work, now!

**Comment by jfagoagas** [comment]
> Hi @jfagoagas!
> 
> It seems to work, now!

Awesome!!! Thanks again!

**Review by jfagoagas — APPROVED** [review]
🚀

**Pull request merged**
