### PR TITLE
fix(opensearch): handle non existing SAMLOptions in domain

### PR DESCRIPTION
**Pull request by MrCloudSec**
### Description

Handle non existing `SAMLOptions` in OpenSearch Domain.

### License

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Review by pedrooot — APPROVED** [review]
LGTM!

**Review by jfagoagas — CHANGES_REQUESTED** [review]
Could you please add `get()` for all the calls in the function? Thanks!

**Comment by MrCloudSec** [comment]
> Could you please add `get()` for all the calls in the function? Thanks!

At which calls do you refer? Remember that we have to do this one by one because since we have to make sure to handle each specific case correctly.

**Comment by jfagoagas** [comment]
> > Could you please add `get()` for all the calls in the function? Thanks!
> 
> At which calls do you refer? Remember that we have to do this one by one because since we have to make sure to handle each specific case correctly.

I meant for all the calls within that function but it's good for now.

**Review by jfagoagas — APPROVED** [review]
🔝

**Pull request merged**
