### PR TITLE
chore(k8s): Add helm-chart

### PR DESCRIPTION
**Pull request by shot4free**
### Context

Adding a helm chart for prowler as discussed here: https://github.com/prowler-cloud/prowler/discussions/4358#discussioncomment-9937217

### Description

Simple helm chart to deploy prowler for k8s.
Implemented additional logics for GKE as one of the paths (/srv/kubernetes) cannot be mounted in GCP clusters.

### License

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Review by MrCloudSec — APPROVED** [review]
Love this @shot4free , thanks!!
Could you add the steps to deploy the helm chart in the README? That would be so helpful.

**Review by MrCloudSec — CHANGES_REQUESTED** [review]
Love this @shot4free , thanks!!
Could you add the steps to deploy the helm chart in the README? That would be so helpful.

**Comment by shot4free** [comment]
> Love this @shot4free , thanks!! Could you add the steps to deploy the helm chart in the README? That would be so helpful.

Done.

**Review by MrCloudSec — APPROVED** [review]
LGTM, thanks @shot4free !

**Pull request merged**
