### PR TITLE
fix extra731 output

### PR DESCRIPTION
**Pull request by gabrielsoltz**
textInfo should be textPass

### CODE REVIEW

**Review by toniblyx — COMMENTED** [review]
I left that as textInfo because I wasn't pretty sure of the results in different setups than mine, if you have tested it enough and think that makes sense that change, please confirm.

**Comment by gabrielsoltz** [comment]
With previous code:

```
 7.31 [extra731] Check if SNS topics have policy set as Public (Not Scored) (Not part of CIS benchmark)
       INFO! eu-north-1: No SNS topics found
       INFO! ap-south-1: No SNS topics found
       INFO! eu-west-3: No SNS topics found
       INFO! eu-west-2: No SNS topics found
       INFO! eu-west-1: SNS topic xxx-alerts has a Condition
       INFO! eu-west-1: SNS topic xxx-topic has a Condition
       INFO! eu-west-1: SNS topic security_list has a Condition
       INFO! ap-northeast-2: No SNS topics found
       INFO! ap-northeast-1: No SNS topics found
       INFO! sa-east-1: No SNS topics found
       INFO! ca-central-1: No SNS topics found
       INFO! ap-southeast-1: No SNS topics found
       INFO! ap-southeast-2: No SNS topics found
       INFO! eu-central-1: No SNS topics found
       INFO! us-east-1: SNS topic xxx-cloudtrail-alerts has a Condition
       INFO! us-east-1: SNS topic xxx-cloudtrail-alerts-insecure has a Condition
       INFO! us-east-2: No SNS topics found
       INFO! us-west-1: No SNS topics found
       INFO! us-west-2: No SNS topics found
```

With New Code:

```
 7.31 [extra731] Check if SNS topics have policy set as Public (Not Scored) (Not part of CIS benchmark)
       INFO! eu-north-1: No SNS topics found
       INFO! ap-south-1: No SNS topics found
       INFO! eu-west-3: No SNS topics found
       INFO! eu-west-2: No SNS topics found
       PASS! eu-west-1: SNS topic xxx-alerts has a Condition
       PASS! eu-west-1: SNS topic xxx-topic has a Condition
       PASS! eu-west-1: SNS topic security_list has a Condition
       INFO! ap-northeast-2: No SNS topics found
       INFO! ap-northeast-1: No SNS topics found
       INFO! sa-east-1: No SNS topics found
       INFO! ca-central-1: No SNS topics found
       INFO! ap-southeast-1: No SNS topics found
       INFO! ap-southeast-2: No SNS topics found
       INFO! eu-central-1: No SNS topics found
       PASS! us-east-1: SNS topic xxx-cloudtrail-alerts has a Condition
       PASS! us-east-1: SNS topic xxx-cloudtrail-alerts-insecure has a Condition
       INFO! us-east-2: No SNS topics found
       INFO! us-west-1: No SNS topics found
       INFO! us-west-2: No SNS topics found
```

**Comment by gabrielsoltz** [comment]
I think is important for counting pass functionality.

**Comment by toniblyx** [comment]
Thanks @gabrielsoltz, are those conditions found working fine for you?

**Comment by gabrielsoltz** [comment]
Yes.

**Pull request merged**
