### PR TITLE
Add additional error checking to check extra769

### PR DESCRIPTION
**Pull request by zfLQ2qx2**
Add additional error checking to check extra769

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Comment by zfLQ2qx2** [comment]
@toniblyx I've raised a new PR for Prowler

**Comment by toniblyx** [comment]
cool, thanks! I'm working on a new function to check AWS CLI version, let me finish it and we can probably add more context to that message.

**Comment by zfLQ2qx2** [comment]
@toniblyx I thought about doing something like that, I could see gating each check individually on the minimum version needed to run it. I could also see doing a minimum version to run prowler and letting people know if their awscli is backlevel or not.

**Comment by toniblyx** [comment]
I'm going to create an issue to track that AWS CLI version discussion and share what I got so far.

**Pull request merged**
