### PR TITLE
feat(inventory): Prowler quick inventory including IAM resources

### PR DESCRIPTION
**Pull request by toniblyx**
### Context 

Please include relevant motivation and context for this PR.

### Description

Please include a summary of the change and which issue is fixed. List any dependencies that are required for this change.

### License

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Review by jfagoagas — CHANGES_REQUESTED** [review]
Please, fulfil the PR body prior to ask for review. Thanks!

**Review by n4ch04 — COMMENTED** [review]
Are we including inventory from services like IAM? 
What if we include that as part of the results to extract added value from that information?

**Review by n4ch04 — COMMENTED** [review]
Do we really need to use temp files? 
I'am going to give it a try changing it to store info in memory

**Review by jfagoagas — CHANGES_REQUESTED** [review]
Please, include error handling for each AWS CLI call.

**Review by jfagoagas — APPROVED** [review]
Let's go!

**Pull request merged**
