### PR TITLE
Improve listing of Checks and Groups

### LINKED ISSUE #545: Enhancement: improve how to handle list of checks and groups
As stated here https://github.com/toniblyx/prowler/pull/541#issuecomment-612933243, as more checks and groups are created more difficult is also to see what is available. 

The idea is to improve the current `-l` and `-L` as in  `./prowler -L` to see all groups and their IDs, `./prowler -l -g cislevel1` to see all checks within that group, and `./prowler -l` if you just wanted a unique list of every single check (assuming none are orphaned outside of all groups and allow grepping for title). A nice-to-have might then be to have each check listed by -l show a comma-separated list of the group(s) that reference it (perhaps coloured), e.g. `4.1  [check41] Ensure no security ... port 22 (Scored) [group4,cislevel1,cislevel2]`

### PR DESCRIPTION
**Pull request by marcjay**
Change `-l` flag to print a unique list of every single check (assuming none are orphaned outside of all groups)
Allow `-g <group_id>` to be specified in combination with `-l`, to only print checks that are referenced by the specified group
When listing all checks with `-l` only, print out all groups that reference each check

Fixes: #545

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Comment by marcjay** [comment]
**Example output**

List all checks:
```
$ ./prowler -l
                          _
  _ __  _ __ _____      _| | ___ _ __
 | '_ \| '__/ _ \ \ /\ / / |/ _ \ '__|
 | |_) | | | (_) \ V  V /| |  __/ |
 | .__/|_|  \___/ \_/\_/ |_|\___|_|v2.2.1
 |_| the handy cloud security tool

 Date: Mon 20 Apr 2020 01:20:46 BST

 Colors code for results:
 INFO (Information), PASS (Recommended value),  FAIL (Fix required),  Not Scored

 1.1  [check11] Avoid the use of the root account (Scored)  [group1, cislevel1, cislevel2, gdpr, hipaa]

 1.2  [check12] Ensure multi-factor authentication (MFA) is enabled for all IAM users that have a console password (Scored)  [group1, cislevel1, cislevel2, gdpr, hipaa]

 1.3  [check13] Ensure credentials unused for 90 days or greater are disabled (Scored)  [group1, cislevel1, cislevel2]

 1.4  [check14] Ensure access keys are rotated every 90 days or less (Scored)  [group1, cislevel1, cislevel2]

 1.5  [check15] Ensure IAM password policy requires at least one uppercase letter (Scored)  [group1, cislevel1, cislevel2]

 1.6  [check16] Ensure IAM password policy require at least one lowercase letter (Scored)  [group1, cislevel1, cislevel2]

 1.7  [check17] Ensure IAM password policy require at least one symbol (Scored)  [group1, cislevel1, cislevel2]

 1.8  [check18] Ensure IAM password policy require at least one number (Scored)  [group1, cislevel1, cislevel2]

 1.9  [check19] Ensure IAM password policy requires minimum length of 14 or greater (Scored)  [group1, cislevel1, cislevel2]

 1.10  [check110] Ensure IAM password policy prevents password reuse: 24 or greater (Scored)  [group1, cislevel1, cislevel2]

 1.11  [check111] Ensure IAM password policy expires passwords within 90 days or less (Scored)  [group1, cislevel1, cislevel2]

 1.12  [check112] Ensure no root account access key exists (Scored)  [group1, cislevel1, cislevel2]
...
```

List all checks in group `hipaa`:
```
$ ./prowler -l -g hipaa
                          _
  _ __  _ __ _____      _| | ___ _ __
 | '_ \| '__/ _ \ \ /\ / / |/ _ \ '__|
 | |_) | | | (_) \ V  V /| |  __/ |
 | .__/|_|  \___/ \_/\_/ |_|\___|_|v2.2.1
 |_| the handy cloud security tool

 Date: Mon 20 Apr 2020 01:30:23 BST

 Colors code for results:
 INFO (Information), PASS (Recommended value),  FAIL (Fix required),  Not Scored

 10.0 HIPAA Compliance - ONLY AS REFERENCE - [hipaa] ****************

 1.2  [check12] Ensure multi-factor authentication (MFA) is enabled for all IAM users that have a console password (Scored)

 1.13  [check113] Ensure MFA is enabled for the root account (Scored)

 2.3  [check23] Ensure the S3 bucket CloudTrail logs to is not publicly accessible (Scored)

 2.6  [check26] Ensure S3 bucket access logging is enabled on the CloudTrail S3 bucket (Scored)

 2.7  [check27] Ensure CloudTrail logs are encrypted at rest using KMS CMKs (Scored)

 2.9  [check29] Ensure VPC Flow Logging is Enabled in all VPCs (Scored)

 7.18 [extra718] Check if S3 buckets have server access logging enabled (Not Scored) (Not part of CIS benchmark)

 7.25 [extra725] Check if S3 buckets have Object-level logging enabled in CloudTrail (Not Scored) (Not part of CIS benchmark)

 7.2 [extra72] Ensure there are no EBS Snapshots set as Public (Not Scored) (Not part of CIS benchmark)

 7.5 [extra75] Ensure there are no Security Groups not being used (Not Scored) (Not part of CIS benchmark)

 7.17 [extra717] Check if Elastic Load Balancers have logging enabled (Not Scored) (Not part of CIS benchmark)

 7.29 [extra729] Ensure there are no EBS Volumes unencrypted (Not Scored) (Not part of CIS benchmark)

 7.34 [extra734] Check if S3 buckets have default encryption (SSE) enabled or use a bucket policy to enforce it (Not Scored) (Not part of CIS benchmark)

 3.8  [check38] Ensure a log metric filter and alarm exist for S3 bucket policy changes (Scored)

 7.3 [extra73] Ensure there are no S3 buckets open to the Everyone or Any AWS user (Not Scored) (Not part of CIS benchmark)

 7.40 [extra740] Check if EBS snapshots are encrypted (Not Scored) (Not part of CIS benchmark)

 7.35 [extra735] Check if RDS instances storage is encrypted (Not Scored) (Not part of CIS benchmark)
```

**Comment by marcjay** [comment]
Looking at merge conflicts now
EDIT: resolved in 71bf414

**Comment by toniblyx** [comment]
Awesome, much better now. Thanks @marcjay

**Comment by toniblyx** [comment]
Hi @marcjay, `./prowler -l` doesn't sort all available checks properly, I remember you made those changes for groups. It is like were sorting by group names instead of by check ID.

**Comment by marcjay** [comment]
Oh, that's odd, I'll take a look tonight

**Comment by marcjay** [comment]
Hey @toniblyx just to make sure we're talking about the same thing, are you referring to these checks not being in order?

```
 1.21 [check121] Do not setup access keys during initial user setup for all IAM users that have a console password (Not Scored)   [group1, cislevel2]

 1.22  [check122] Ensure IAM policies that allow full "*:*" administrative privileges are not created (Scored)  [group1, cislevel1, cislevel2, gdpr, iso27001]

 7.74 [extra774] Ensure credentials unused for 30 days or greater are disabled   [group1, extras]

 2.1  [check21] Ensure CloudTrail is enabled in all regions (Scored)  [group2, cislevel1, cislevel2, forensics-ready, gdpr, hipaa, pci, iso27001]
```

and
```
 7.98 [extra798] Check if Lambda functions have resource-based policy set as Public   [extras, internet-exposed]

 7.99 [extra799] Check if Security Hub is enabled and its standard subscriptions   [extras]

 7.100 [extra7100] Ensure that no custom policies exist which allow permissive role assumption (e.g. sts:AssumeRole on *)   [extras]

 7.59 [extra759] Find secrets in Lambda functions variables (Not Scored) (Not part of CIS benchmark)   [secrets]
```

If so, yes that ordering comes from the order of the checks within each group (overall in group order). I can experiment with sorting numerically, ignoring the groupings if you'd like?

**Comment by toniblyx** [comment]
Exactly, if you can try would be great, I can give it a look tomorrow too. Thanks!

**Comment by marcjay** [comment]
No worries, I've put out #649 - I've made no attempt to hide the fact it is a little kludgey in that it relies on 'check' and 'extra' being the same character length - no doubt there may well be better ways to implement it!

**Pull request merged**
