### PR TITLE
fix(sns): allow default SNS policy with SourceOwner

### PR DESCRIPTION
**Pull request by christiandavilakoobin**
### Context

Prowler alerts for sns public accessibilty checks on topics that are generated from the AWS console.

### Description

The AWS console uses the not very well documented AWS:SourceOwner attribute on defaults policies: https://github.com/awsdocs/iam-user-guide/issues/111

### License

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Review by jfagoagas — CHANGES_REQUESTED** [review]
Good catch!! 

Please include tests for the `policy_condition_parser` library.

**Comment by christiandavilakoobin** [comment]
Done! I don't find how to run the tests localy before the PR. I checked the CONTRIB docs, but it only says how to create or modify the tests, but not how to run them.

**Comment by MrCloudSec** [comment]
> Done! I don't find how to run the tests localy before the PR. I checked the CONTRIB docs, but it only says how to create or modify the tests, but not how to run them.

You have to do a `pre-commit install` inside the repo :) You can see more in our [Developer Guide](https://docs.prowler.cloud/en/latest/tutorials/developer-guide/)

**Review by jfagoagas — APPROVED** [review]
Thanks again @christiandavilakoobin !

I've fixed some tests, so this will be merged once the CI pass.

**Pull request merged**
