### PR TITLE
feat(check): Directory Service - Ensure Radius server is using the recommended security protocol

### PR DESCRIPTION
**Pull request by rajarshidas**
### Context 

1. CIS End User Compute 2.18. CIS Level 2 Benchmark for AWS Directory Service - Radius Server recommended security protocol
2. CIS End User Compute 3.2. CIS Level 2 Benchmark for AWS Directory Service - Radius Server MFA is enabled successfully in the directory service.

### Description

1. This checks on the Radius server associated with the directory service directory, whether it's using the recommended security protocol
2. Multi-Factor Authentication (MFA) adds an extra layer of authentication assurance beyond traditional username and password. With MFA enabled, when a user signs in to Amazon WorkDocs, which leverages the Directory Service configured Radius MFA, they will be prompted for their user name and password as well as for an authentication code from their MFA token.

### License

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### License

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Comment by MrCloudSec** [comment]
Awesome, thanks @rajarshidas we will give it a look and let you know soon if we have any comment or suggestion

**Comment by MrCloudSec** [comment]
@rajarshidas we have added some changes to the check, we are pending to test it in a real environment.

**Comment by rajarshidas** [comment]
Thanks @sergargar and @toniblyx ! This is my second PR and I intend to contribute more. Is there a guide on how best to place a 'check' in a 'group'. This check is for a CIS Level 2 group, so I created the check and group changes that way. I see that these have been moved to the 'extra' section. Would be great to have some guidance on this for future commits.

**Comment by toniblyx** [comment]
Thank you @rajarshidas, we are looking for people that use Prowler custom checks to give me feedback for the next version of Prowler. I’ll put a Prowler Pro hat in your mailbox. If you are interested, please, fill out this form https://lnkd.in/eJi8MqhA

**Comment by rajarshidas** [comment]
> Thank you @rajarshidas, we are looking for people that use Prowler custom checks to give me feedback for the next version of Prowler. I’ll put a Prowler Pro hat in your mailbox. If you are interested, please, fill out this form https://lnkd.in/eJi8MqhA

@toniblyx  Much appreciated and form submission done!

**Comment by rajarshidas** [comment]
@sergargar and @toniblyx, I have added the following check on this PR as well for your review: CIS End User Compute 3.2. CIS Level 2 Benchmark for AWS Directory Service - Radius Server MFA is enabled successfully in the directory service.

Thanks.

**Comment by MrCloudSec** [comment]
Thank you again for your contribution @rajarshidas, the checks look great!!

**Review by MrCloudSec — DISMISSED** [review]

**Review by MrCloudSec — APPROVED** [review]

**Pull request merged**
