### PR TITLE
adapt check119 to exclude instances shutting down... this time with correct check...

### PR DESCRIPTION
**Pull request by stku1985**
brain fart: used logical 'or' instead of correct '&&'. Sorry about that.
this really fixes issue https://github.com/toniblyx/prowler/issues/689

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Comment by toniblyx** [comment]
Are you sure? Can an instance be in two states at the same time?

**Comment by toniblyx** [comment]
based on https://docs.aws.amazon.com/cli/latest/reference/ec2/describe-instances.html instance-state-name - The state of the instance (pending | running | shutting-down | terminated | stopping | stopped ), hence OR should work and AND shouldn't.

**Comment by stku1985** [comment]
I am pretty sure that we only want to check if the ec2 instance is both not "terminated" _and_ not "shutting-down", that is if it is either pending, running, stopping or stopped. I do not claim that an instance can be in two states at once ^^.

**Review by toniblyx — APPROVED** [review]

**Comment by toniblyx** [comment]
I get it, tested and ok.

**Pull request merged**
