### PR TITLE
New check 7148 EFS File systems have backup enabled @georgie969

### PR DESCRIPTION
**Pull request by georgie969**
By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license. This Pull request is called [extra7148] to Check if EFS has backup enabled

### CODE REVIEW

**Review by w0rmr1d3r — COMMENTED** [review]
I do have a question, what if AWS Backup is doing backups for an EFS instead of the EFS having backups enabled, can that be possible?
What would happen to that check if it is possible?

**Comment by georgie969** [comment]
_"I do have a question, what if AWS Backup is doing backups for an EFS instead of the EFS having backups enabled, can that be possible? What would happen to that check if it is possible?"_

----------

**If AWS Backup is doing backups for EFS, The check still reports the same information. I have tested this scenario by creating a backup via AWS Backup, using EFS as the resource. After the Backup was created for that specific File system using AWS Backup, its recognized that the specific File system has a backup policy attached and the same principles apply.**

**Review by w0rmr1d3r — APPROVED** [review]
Careful, modify the PR title, since it's refering to check 7148, but it's actually doing 7149 !

**Comment by georgie969** [comment]
Yes, Thank you. I made an error and submitted a different Custom Check 7149 which is for a different service "Redshift" under the same pull request. I will remove that. Thank you

**Review by w0rmr1d3r — APPROVED** [review]
looks good to me :) nice work!

**Comment by georgie969** [comment]
Hi @w0rmr1d3r I made an error and submitted two different Prowler checks on the same Pull request. Can you kindly roll back the approvals so I can make two separate branches and two new pull requests? One for the EFS Prowler Check and another for the Redshift Prowler Check? Thank you

**Comment by georgie969** [comment]
@w0rmr1d3r  Okay. I have deleted the 7149 Redshift Check and This Prowler check 7148 is good to go! Thank you!

**Comment by toniblyx** [comment]
Good job! Thanks!

**Comment by georgie969** [comment]
> Good job! Thanks!

You are welcome! Much appreciation!

**Pull request merged**
