### PR TITLE
Sorted output to have a fixed list for diff.

### PR DESCRIPTION
**Pull request by martinusnel**
Sort output so that we can diff between runs.

### CODE REVIEW

**Review by toniblyx — APPROVED** [review]
Thanks @martinusnel, it makes sense.

**Comment by toniblyx** [comment]
Hello @martinusnel, I don´t know either what happened with this check. Can you test this code and I can put it back to the repo?
```
#!/usr/bin/env bash

# Prowler - the handy cloud security tool (c) by Toni de la Fuente
#
# This Prowler check is licensed under a
# Creative Commons Attribution-NonCommercial-ShareAlike 4.0 International License.
#
# You should have received a copy of the license along with this
# work. If not, see <http://creativecommons.org/licenses/by-nc-sa/4.0/>.

CHECK_ID_check45="4.5,4.05"
CHECK_TITLE_check45="[check45] Ensure routing tables for VPC peering are \"least access\" (Not Scored)"
CHECK_SCORED_check45="NOT_SCORED"
CHECK_TYPE_check45="LEVEL2"
CHECK_ALTERNATE_check405="check45"

check45(){
  # "Ensure routing tables for VPC peering are \"least access\" (Not Scored)"
  textInfo "Looking for VPC peering in all regions...  "
  for regx in $REGIONS; do
    # Sort output so that we can diff between runs.
    LIST_OF_VPCS_PEERING_CONNECTIONS=$(printf '%s\n' $($AWSCLI ec2 describe-vpc-peering-connections --output text $PROFILE_OPT --region $regx --query 'VpcPeeringConnections[*].VpcPeeringConnectionId') | sort | paste -s -d" " -)
    if [[ $LIST_OF_VPCS_PEERING_CONNECTIONS ]];then
      textInfo "$regx: $LIST_OF_VPCS_PEERING_CONNECTIONS - review routing tables" "$regx"
      #LIST_OF_VPCS=$($AWSCLI ec2 describe-vpcs $PROFILE_OPT --region $regx --query 'Vpcs[*].VpcId' --output text)
      #aws ec2 describe-route-tables --filter "Name=vpc-id,Values=vpc-0213e864" --query "RouteTables[*].{RouteTableId:RouteTableId, VpcId:VpcId, Routes:Routes, AssociatedSubnets:Associations[*].SubnetId}" $PROFILE_OPT --region $regx
      # for vpc in $LIST_OF_VPCS; do
      #   VPCS_WITH_PEERING=$($AWSCLI ec2 describe-route-tables --filter "Name=vpc-id,Values=$vpc" $PROFILE_OPT --region $regx --query "RouteTables[*].{RouteTableId:RouteTableId, VpcId:VpcId, Routes:Routes, AssociatedSubnets:Associations[*].SubnetId}" |grep GatewayId|grep pcx-)
      # done
      #echo $VPCS_WITH_PEERING
    else
      textPass "$regx: No VPC peering found" "$regx"
    fi
  done
}
```

Can you please also shere with me an output with and without `paste` command?

**Comment by toniblyx** [comment]
ok ok, I know what has happened, my bad memory... In the latest AWS CIS Benchmark recommendations they deleted check 4.5 so I deleted it as well. Check the guide TOC here https://d0.awsstatic.com/whitepapers/compliance/AWS_CIS_Foundations_Benchmark.pdf in any case I could move it to extras... Thoughts?

**Comment by martinusnel** [comment]
I am more interested in the resulting check44, which is just the new name of check45, having sorted output :)

The magic bit is: `| sort | paste -s -d" " -`.

Do you want me to do a PR for the new check44?

**Comment by toniblyx** [comment]
Ok, I get it. Can you please share the output of the current check, also with and without `-M csv` and the new check with your suggested options? We need to make sure we don't break anybody else output diffs. I know about lots of people doing diffs between Prowler csv or json outputs and I shouldn't ruin their day ;)

**Comment by martinusnel** [comment]
Not a problem, please see attached.

Please note that without the sort you cannot diff as the AWS CLI output is not deterministic at all. It is potentially different on each run.  Example - and other than redaction, not modified to suite my argument :)

```
15:40 $ aws ec2 describe-vpc-peering-connections --output text --profile dev --query 'VpcPeeringConnections[*].VpcPeeringConnectionId'
pcx-555    pcx-222    pcx-111    pcx-444    pcx-333

15:41 $ aws ec2 describe-vpc-peering-connections --output text --profile dev --query 'VpcPeeringConnections[*].VpcPeeringConnectionId'
pcx-333    pcx-222    pcx-111    pcx-555    pcx-444
```
The original change, as was excepted, will not work in any case as I forgot to translate the tabs to newlines so that sort can actually work :)

` | tr '\t' '\n' | sort | paste -s -d"\t" - `

All private information redacted in attached files.  The peers themselves (pcx-...) has been replaced by 111 - 555 and correctly represented as I just used a recursive search/replace.

[after_change_csv.txt](https://github.com/toniblyx/prowler/files/2353213/after_change_csv.txt)
[after_change_html.txt](https://github.com/toniblyx/prowler/files/2353214/after_change_html.txt)
[before_change_csv.txt](https://github.com/toniblyx/prowler/files/2353215/before_change_csv.txt)
[before_change_html.txt](https://github.com/toniblyx/prowler/files/2353216/before_change_html.txt)

**Comment by martinusnel** [comment]
Do you need any further information?

**Comment by toniblyx** [comment]
Thanks @martinusnel, it is all right, I'll work on it as soon as possible :)

**Pull request merged**
