### PR TITLE
Fix listing configurations if default output format is not JSON

### PR DESCRIPTION
**Pull request by Anthirian**
By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

This prevents errors like:
```
parse error: Invalid numeric literal at line 1, column 2 
```

### CODE REVIEW

**Comment by toniblyx** [comment]
Thanks @Anthirian, I guess you need that change because your AWSCLI is not configured to use json by default, right?

**Comment by Anthirian** [comment]
Yes correct, I have no default output format configured.

**Comment by toniblyx** [comment]
That's a bit weird because cli output is json by default, what output do you get instead? I don't think your suggested changes will break anything so it will be merged after a test. Thanks.

**Comment by Anthirian** [comment]
Maybe it had to do with the fact that I originally set it to a different format, but modified the config files to remove that part. In any case I don't think it will be harmful to explicitly state the desired output. In fact it may prove more robust in the future.

**Pull request merged**
