### PR TITLE
Check extra727 smarter (SQS)

### PR DESCRIPTION
**Pull request by gabrielsoltz**
- Using jq to identify each policy statement
- Conditions are now by statement
- Output specify who can do what
- Identifying policies with and without conditions, different output

### CODE REVIEW

**Comment by toniblyx** [comment]
I'm not sure if it is good to add that much dependency on `jq` in Prowler but I guess it is needed for more accurate results. In your experience, how different are the results?

**Comment by gabrielsoltz** [comment]
I reduced 1 API call for this check.

**Comment by gabrielsoltz** [comment]
fewer api calls.

**Comment by toniblyx** [comment]
LGTM, thanks @gabrielsoltz, good job!

**Pull request merged**
