### PR TITLE
docs(azure): audit_info updated to provider

### PR DESCRIPTION
**Pull request by Hugo966**
### Context

audit_info doc updated to provider

### Description

Documentation in developer guide about audit_info updated to provider, which is what we right now have in Prowler V4.
We don't use audit_info anymore, we now have the provider file for each provider which works better, that's what im updating in the documentation here.

### License

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Comment by sergargar** [comment]
Please, update it also in `unit-testing.md`.

**Review by MrCloudSec — CHANGES_REQUESTED** [review]
Please, update it also in unit-testing.md.

**Comment by MrCloudSec** [comment]
Please, improve the PR description and include the documentation about the `set_mocked_<provider>_provider` function.

**Comment by jfagoagas** [comment]
Closed in favor of https://github.com/prowler-cloud/prowler/pull/3756

**Pull request closed without merging**
