### PR TITLE
HTML Report: Filtering and other nice things.

### PR DESCRIPTION
**Pull request by nickmalcolm**
By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

This pull request makes a number of improvements to the HTML output. "Improvements" is subjective though, so I've left the commits unsquashed so you can see the thought process, recommend changes, or reject commits that aren't appropriate.

The goal was to make the HTML output more usable. It does this in the following ways:

  - Filters! Using [DataTables' SearchPanes](https://datatables.net/extensions/searchpanes/examples/initialisation/simple.html) we can allow users to narrow down the table to, for example, everything that failed in IAM rated Medium or above. Or to all the issues in us-east-1. Huge improvement!
  - Totals! SearchPanes can also show us running totals based on what we've selected. This can help us determine what areas might need to be focussed on.
  - Removed the status icon to save room. As there is a textual PASS/INFO/FAIL column _and_ colour coding, we don't need an icon taking up room.
  - Replaced documentation links with the 'standard' external link icon using FontAwesome. Again, a space saver.
  - Fixed a bug (?) where pages were ordering by seemingly random columns.

To achieve this I also tidied up some code duplication and rejigged the javascript.

No new dependencies were introduced (except a native DataTables extension).

## Before

Screen Shot 2021-06-14 at 9 37 01 PM

Note the weird ordering, the table running off the page. (And scoring information not showing up - I don't think I broke that).

## After

No filters applied, showing all totals.

Screen Shot 2021-06-14 at 9 37 20 PM

With filters applied, showing filtered total and overall totals.

Screen Shot 2021-06-14 at 9 37 40 PM

Note that in this case I'm running it against a single AWS account. If there were multiple, SearchPanes would be smart enough to dynamically add a pane to let users show only certain accounts. Panes are also dynamically responsive to page width.

## Next Steps

If you'd like I can sanitise and upload a copy of the new report, but I figured reviewers might want to run it locally themselves.

As I said earlier, feel free to comment on individual commits.

**Todo:** 

  - Assuming this is all good, I spotted that `generate-html-from-csv.sh` will need to be updated. It already looks like it's missing some changes - scoring in the header, risk, remediation, and documentation links in the rows.
  - For some reason, even running off your `master` branch, the scoring information in the top right didn't appear to work. I don't think it's a bug I introduced...

### CODE REVIEW

**Comment by w0rmr1d3r** [comment]
Nice @nickmalcolm !
I'm gonna take a look soon!
Regarding this:
> For some reason, even running off your master branch, the scoring information in the top right didn't appear to work. I don't think it's a bug I introduced...

Take a look at this issue -> https://github.com/toniblyx/prowler/issues/815

**Comment by toniblyx** [comment]
Awesome, I love these kind of PR :D

**Review by w0rmr1d3r — COMMENTED** [review]
Looks great!
Question, why are we deleting some dependencies?

**Comment by nickmalcolm** [comment]
I don't think we are, but please do double check. I've cleaned up duplicate dependencies. 

Popper is included in bootstrap bundle. And you choose either bootstrap bundle, OR bootstrap. Not both. https://getbootstrap.com/docs/4.0/getting-started/contents/#js-files

**Comment by w0rmr1d3r** [comment]
> I don't think we are, but please do double check. I've cleaned up duplicate dependencies.
> 
> Popper is included in bootstrap bundle. And you choose either bootstrap bundle, OR bootstrap. Not both. https://getbootstrap.com/docs/4.0/getting-started/contents/#js-files

That might be it! Thanks!

**Comment by toniblyx** [comment]
Thank you both! I´m merging it to devel branch 2.5. Remember I had already   `echo '  <td>'$CHECK_RESOURCE_ID'</td>' >> ${OUTPUT_FILE_NAME}.$EXTENSION_HTML` in that file in 2.5 so I have left that parameter too.

**Comment by toniblyx** [comment]
@nickmalcolm look at this screenshot, severity and service is getting the ascii characters of the new implementation in 2.5, I guess you haven't played with it yet.
Screenshot 2021-06-14 at 2 57 13 PM

**Comment by nickmalcolm** [comment]
Ah, I hadn't seen that. Good spotting! I'll look in to it tonight and create a PR against the 2.5 branch.

**Comment by nickmalcolm** [comment]
@toniblyx I checked out 1229815c04909cfd55cbd529ed5dbc903e90d175 which represents branch 2.5 before my changes were merged in. Running prowler gives output as shown in the screenshot below. The HTML output contains those ASCII characters already. So, in the changes this PR introduced, SearchPanes is just taking the content directly from the table cells.

Is the table content supposed to look different to this?

Screen Shot 2021-06-15 at 7 56 35 PM

I'm happy to fix up anything that I might have broken, I just need to understand what that was 😅

**Comment by toniblyx** [comment]
Sorry, I didn't explain that properly. I added a couple of changes in 2.5 to those columns header. I need to review it in detail to remove this characters.

**Pull request merged**
