### PR TITLE
New check for ecr findings

### PR DESCRIPTION
**Pull request by nexeck**
By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

This will check if there are any images with findings inside ecr.
At the moment it will not check the severities of those findings, i found this list of severities, maybe we could ignore INFORMATIONAL?

- "HIGH"
- "MEDIUM"
- "INFORMATIONAL"
- "LOW"
- "CRITICAL"
- "UNDEFINED"

Is there a way to configure such checks?

### CODE REVIEW

**Comment by toniblyx** [comment]
Thanks @nexeck, it would be better to show severity, even informational with textInfo. Could you add that please? 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by nexeck** [comment]
Should we show only the highest, or all which were found? @toniblyx

**Comment by nexeck** [comment]
Something like this could also be possible
image

**Comment by nexeck** [comment]
Would also be possible, to show only high, critical, medium as fail, and all others as info, what do you think?
Could look like:
image

**Comment by toniblyx** [comment]
I like it, I think it is pretty helpful and gives good information about what it is.

**Comment by nexeck** [comment]
@toniblyx I have pushed the changes from the last screenshot :-)

**Pull request merged**
