### PR TITLE
chore(logo): Add Prowler logo in SVG format & Propose to Prowler icon design

### PR DESCRIPTION
**Pull request by dsict**
### Context
Created prowler logo and icon in svg format.
I think it would be nice if the Prowler icon used the first letter of the logo like the pro version.

### License
By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Comment by toniblyx** [comment]
Thanks @dsict, it looks cool! 

Quick question, why did you add `prowler-logo..svg` with double dot? is it a typo?

**Comment by dsict** [comment]
The answer to your quick question: **It's a typing error**.
Sorry for the error. I fix it.

Thanks! @toniblyx

**Comment by WANZARGEN** [comment]
wow, lovely! 💓

**Review by MrCloudSec — APPROVED** [review]
This is awesome @dsict , thank you!!
I have added the new icon to our public docs 👏🏼

**Pull request merged**
