### PR TITLE
feat(compliance): New AWS Performance Pillar Framework

### PR DESCRIPTION
**Pull request by akshat-crypto**
### Context

To add a new customized pillar in AWS Well Architected Framework 

### Description

There are almost 6 AWS Well Architected Review Pillars we can use , I am currently adding Performance Pillar to test how this will work, and based on the review, we can create multiple custom checks

### CODE REVIEW

**Review by MrCloudSec — CHANGES_REQUESTED** [review]
thanks for you PR! here’s my first review:
- the metadata for the check `ec2_instance_type_optimized` is missing (https://docs.prowler.cloud/en/latest/developer-guide/checks/#check-metadata)
- the logic of `serverless_architecture` in the Lambda Service is needed
- the logic of `is_instance_type_optimized` in the EC2 Service is needed
- please, restore the changes in the `banner.py` file

Let me know if you need help with any of this points 😄

**Review by MrCloudSec — CHANGES_REQUESTED** [review]
I’ve just fix a typo in the name of your metadata file. Please, do the following changes:

- revert the changes done on the `awslambda_function_not_publicly_accessible` check
- the logic of `serverless_architecture` in the Lambda Service is needed
- the logic of `is_instance_type_optimized` in the EC2 Service is needed

We can have a quick call if you need help :slightly_smiling_face:

**Comment by MrCloudSec** [comment]
Hi @akshat-crypto , do you need help on adding the needed logic in the services?

**Comment by jfagoagas** [comment]
Hello @akshat-crypto we will close this PR. We have created this issue https://github.com/prowler-cloud/prowler/issues/4638 to keep track of the AWS Performance Pillar Framework implementation. We will use the work you did which is fantastic to complete the missing code from the review that @sergargar did.

Thank you for contributing with Prowler!

**Pull request closed without merging**
