### PR TITLE
Add additional action permissions for Glue and Shield Advanced checks @lazize

### LINKED ISSUE #994: An error occurred (AccessDeniedException) when calling the GetSubscriptionState operation
On branch 2.7 there are new checks that uses command `aws shield get-subscription-state`.

https://github.com/toniblyx/prowler/blob/d7b360629dd35043853dadd7545baa6b37617297/checks/check_extra7169#L28

But standard role doesn't add permission to action `shield:GetSubscriptionState`.
Managed policies add permission to perform only actions `Describe*` and `List*`.

https://github.com/toniblyx/prowler/blob/2.7/iam/create_role_to_assume_cfn.yaml

----

```shell
7.166 [extra7166] Check if Elastic IP addresses with associations are protected by AWS Shield Advanced - shield [Medium]

An error occurred (AccessDeniedException) when calling the GetSubscriptionState operation: User: arn:aws:sts::xxxxxxxx1531:assumed-role/ProwlerExecRole/ProwlerAssessmentSession is not authorized to perform: shield:GetSubscriptionState on resource: arn:aws:shield::xxxxxxxx1531:subscription/* because no identity-based policy allows the shield:GetSubscriptionState action
       INFO! No AWS Shield Advanced subscription found. Skipping check.
7.167 [extra7167] Check if Cloudfront distributions are protected by AWS Shield Advanced - shield [Medium]

An error occurred (AccessDeniedException) when calling the GetSubscriptionState operation: User: arn:aws:sts::xxxxxxxx1531:assumed-role/ProwlerExecRole/ProwlerAssessmentSession is not authorized to perform: shield:GetSubscriptionState on resource: arn:aws:shield::xxxxxxxx1531:subscription/* because no identity-based policy allows the shield:GetSubscriptionState action
       INFO! No AWS Shield Advanced subscription found. Skipping check.
7.168 [extra7168] Check if Route53 hosted zones are protected by AWS Shield Advanced - shield [Medium]

An error occurred (AccessDeniedException) when calling the GetSubscriptionState operation: User: arn:aws:sts::xxxxxxxx1531:assumed-role/ProwlerExecRole/ProwlerAssessmentSession is not authorized to perform: shield:GetSubscriptionState on resource: arn:aws:shield::xxxxxxxx1531:subscription/* because no identity-based policy allows the shield:GetSubscriptionState action
       INFO! No AWS Shield Advanced subscription found. Skipping check.
7.169 [extra7169] Check if global accelerators are protected by AWS Shield Advanced - shield [Medium]

An error occurred (AccessDeniedException) when calling the GetSubscriptionState operation: User: arn:aws:sts::xxxxxxxx1531:assumed-role/ProwlerExecRole/ProwlerAssessmentSession is not authorized to perform: shield:GetSubscriptionState on resource: arn:aws:shield::xxxxxxxx1531:subscription/* because no identity-based policy allows the shield:GetSubscriptionState action
       INFO! No AWS Shield Advanced subscription found. Skipping check.
7.170 [extra7170] Check if internet-facing application load balancers are protected by AWS Shield Advanced - shield [Medium]

An error occurred (AccessDeniedException) when calling the GetSubscriptionState operation: User: arn:aws:sts::xxxxxxxx1531:assumed-role/ProwlerExecRole/ProwlerAssessmentSession is not authorized to perform: shield:GetSubscriptionState on resource: arn:aws:shield::xxxxxxxx1531:subscription/* because no identity-based policy allows the shield:GetSubscriptionState action
       INFO! No AWS Shield Advanced subscription found. Skipping check.
7.171 [extra7171] Check if classic load balancers are protected by AWS Shield Advanced - shield [Medium]

An error occurred (AccessDeniedException) when calling the GetSubscriptionState operation: User: arn:aws:sts::xxxxxxxx1531:assumed-role/ProwlerExecRole/ProwlerAssessmentSession is not authorized to perform: shield:GetSubscriptionState on resource: arn:aws:shield::xxxxxxxx1531:subscription/* because no identity-based policy allows the shield:GetSubscriptionState action
       INFO! No AWS Shield Advanced subscription found. Skipping check.
```

### PR DESCRIPTION
**Pull request by lazize**
Allows the shield:GetSubscriptionState action

Fix #994 

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Comment by toniblyx** [comment]
In addition to `iam/create_role_to_assume_cfn.yaml` there are other files that require that change:

./iam/prowler-additions-policy.json
./util/codebuild/codebuild-prowler-audit-account-cfn.yaml
./util/terraform-kickstarter/main.tf

Would you mind to add it in those files as well? and if you add glue:GetSecurityConfiguration we can also close #988 :) 

Thanks!

**Comment by toniblyx** [comment]
And `shield:DescribeProtection` is also required.

**Comment by lazize** [comment]
`shield:Describe*` is already covered by managed policy `SecurityAudit`, so it should not be necessary to add it explicit.

./iam/create_role_to_assume_cfn.yaml
* Missing `glue:GetSecurityConfiguration`, will add it
* Added `shield:GetSubscriptionState` on previews commit

./iam/prowler-additions-policy.json
* Missing `glue:GetSecurityConfiguration`, will add it
* Already has `shield:GetSubscriptionState`

./util/codebuild/codebuild-prowler-audit-account-cfn.yaml
* Missing `glue:GetSecurityConfiguration`, will add it
* Already has `shield:GetSubscriptionState`

./util/terraform-kickstarter/main.tf
* Missing `glue:GetSecurityConfiguration`, will add it
* Already has `shield:GetSubscriptionState`

----

See below permission actions from all files above.
As you can see they don't match exactly, should they?

File `./iam/prowler-additions-policy.json` has action `glue:SearchTables` which doesn't exist on others.

./iam/create_role_to_assume_cfn.yaml
```yaml
              Action:
                - 'ds:ListAuthorizedApplications'
                - 'ec2:GetEbsEncryptionByDefault'
                - 'ecr:Describe*'
                - 'support:Describe*'
                - 'tag:GetTagKeys'
                - 'lambda:GetFunction'
                - 'glue:GetConnections'
                - 's3:GetAccountPublicAccessBlock'
                - 'shield:GetSubscriptionState'
```

./iam/prowler-additions-policy.json
```json
            "Action": [
                "ds:ListAuthorizedApplications",
                "ec2:GetEbsEncryptionByDefault",
                "ecr:Describe*",
                "support:Describe*",
                "tag:GetTagKeys",
                "lambda:GetFunction",
                "glue:GetConnections",
                "glue:SearchTables",
                "s3:GetAccountPublicAccessBlock",
                "shield:GetSubscriptionState",
                "shield:DescribeProtection"
            ],
```

./util/codebuild/codebuild-prowler-audit-account-cfn.yaml
```yaml
              - Action:
                  - s3:GetAccountPublicAccessBlock
                  - glue:GetConnections
                  - glue:SearchTables
                  - ds:ListAuthorizedApplications
                  - ec2:GetEbsEncryptionByDefault
                  - ecr:Describe*
                  - support:Describe*
                  - tag:GetTagKeys
                  - lambda:GetFunction
                  - shield:GetSubscriptionState
                  - shield:DescribeProtection
```

./util/terraform-kickstarter/main.tf
```tf
        Action =  [
                  "s3:GetAccountPublicAccessBlock",
                  "glue:GetConnections",
                  "glue:SearchTables",
                  "ds:ListAuthorizedApplications",
                  "ec2:GetEbsEncryptionByDefault",
                  "ecr:Describe*",
                  "support:Describe*",
                  "tag:GetTagKeys",
                  "lambda:GetFunction",
                  "shield:GetSubscriptionState",
                  "shield:DescribeProtection"
                  ]
```

**Comment by toniblyx** [comment]
They all should be the same because are for the same purpose (11 lines).

**Comment by toniblyx** [comment]
Awesome, great job @lazize!

**Pull request merged**
