### PR TITLE
pipenv: add lockfile

### PR DESCRIPTION
**Pull request by chenrui333**
Add lockfile for reproducible build

### CODE REVIEW

**Comment by toniblyx** [comment]
Thanks @chenrui333, can you explain a bit the reason of this change? I see you are maintatiner of Homebrew, is that somehow related?

**Comment by chenrui333** [comment]
> Thanks @chenrui333, can you explain a bit the reason of this change? I see you are maintatiner of Homebrew, is that somehow related?

Yeah, totally

Ideally, it would be great to leverage the lockfile to build from the source as it is (which I intended to bring it to the homebrew side), but I run into some issue (I will post it later on this).

But in general, I think it is preferred to have lockfile version controlled along with the source code.

**Comment by toniblyx** [comment]
Could you please point me to some documentation to better understand what you are willing to do? Thanks.

**Comment by toniblyx** [comment]
Since I haven't had more information about this I'll close it. Please feel free to reopen it and provide more information about packaging Prowler for Homebrew.

**Pull request closed without merging**
