### PR TITLE
New check 7164 Check if EFS has backup policy enabled @maisenhe

### PR DESCRIPTION
**Pull request by maisenhe**
By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
Check if EFS has backup policy enabled

### CODE REVIEW

**Comment by toniblyx** [comment]
Thanks @maisenhe, that checks is already written, it is actually  `extra7148`.

**Comment by toniblyx** [comment]
We are working on a public list of checks to write to make that easier for the community. Do you want ideas? What about a check to look for `Cloudwatch log group encrypted` or `CloudFront distribution pointing to non existing buckets to prevent subdomain hijacking`?

**Comment by maisenhe** [comment]
@toniblyx when you are talking about log group encryption are you talking about having AWS Key Management Service for this encryption? As Log group data is always encrypted in CloudWatch Logs. Thanks

**Comment by toniblyx** [comment]
exactly, with kms.

**Pull request closed without merging**
