### PR TITLE
chore: modify latest version msg

### PR DESCRIPTION
**Pull request by R3DRUN3**
### Context

This PR updates the latest version message to enhance user engagement and clarity.  
The change from `it is the latest version` to `You are running the latest version` adds a personal touch, making the message feel more user-centric.  
This small adjustment aims to create a more positive and user-friendly experience, reinforcing the idea that the user is in control and up-to-date.

### Description

Safe to merge *PR*: just modified the message for the latest version.

### License

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Comment by MrCloudSec** [comment]
Hi @R3DRUN3, I like that personal touch, thanks!
Please, in order to pass our tests, can you run our pre-commit? or just execute the black library `poetry run black .` ?

**Comment by R3DRUN3** [comment]
> poetry run black .

@sergargar I've run the code formatter, the PR should pass the tests now! 😊

**Review by MrCloudSec — DISMISSED** [review]

**Comment by MrCloudSec** [comment]
It seems that you have an old version of `black`, can you do a `poetry install`? Also, please discard the changes in `tests/providers/aws/services/iam/iam_inline_policy_no_administrative_privileges/iam_inline_policy_no_administrative_privileges_test.py` file.

**Comment by R3DRUN3** [comment]
> iam_inline_policy_no_administrative_privileges_test.py

@sergargar  Done!

**Comment by MrCloudSec** [comment]
> > iam_inline_policy_no_administrative_privileges_test.py
> 
> 
> 
> @sergargar  Done!

I still see changes in that file 😕

**Comment by R3DRUN3** [comment]
Closing this, I'll submit a new PR in the future

**Pull request closed without merging**
