### PR TITLE
Quotes to output file

### PR DESCRIPTION
**Pull request by xavier-sky**
Necessary quotes to process the special characters of the output file and avoid errors when writing the results of the scan.

### Context

When trying to run prowler in macOS I've had some problems related with writing the results of the scan. The errors are:

./include/outputs: line 72: ${OUTPUT_FILE_NAME}.$EXTENSION_HTML: ambiguous redirect

./include/outputs: line 415: ${OUTPUT_FILE_NAME}.$EXTENSION_HTML: ambiguous redirect
./include/outputs: line 416: ${OUTPUT_FILE_NAME}.$EXTENSION_HTML: ambiguous redirect
./include/outputs: line 417: ${OUTPUT_FILE_NAME}.$EXTENSION_HTML: ambiguous redirect
./include/outputs: line 418: ${OUTPUT_FILE_NAME}.$EXTENSION_HTML: ambiguous redirect
./include/outputs: line 419: ${OUTPUT_FILE_NAME}.$EXTENSION_HTML: ambiguous redirect
./include/outputs: line 420: ${OUTPUT_FILE_NAME}.$EXTENSION_HTML: ambiguous redirect
./include/outputs: line 421: ${OUTPUT_FILE_NAME}.$EXTENSION_HTML: ambiguous redirect
./include/outputs: line 422: ${OUTPUT_FILE_NAME}.$EXTENSION_HTML: ambiguous redirect
./include/outputs: line 423: ${OUTPUT_FILE_NAME}.$EXTENSION_HTML: ambiguous redirect
./include/outputs: line 424: ${OUTPUT_FILE_NAME}.$EXTENSION_HTML: ambiguous redirect
./include/outputs: line 425: ${OUTPUT_FILE_NAME}.$EXTENSION_HTML: ambiguous redirect
./include/outputs: line 426: ${OUTPUT_FILE_NAME}.$EXTENSION_HTML: ambiguous redirect
./include/outputs: line 427: ${OUTPUT_FILE_NAME}.$EXTENSION_HTML: ambiguous redirect
./include/outputs: line 428: ${OUTPUT_FILE_NAME}.$EXTENSION_HTML: ambiguous redirect
./include/outputs: line 429: ${OUTPUT_FILE_NAME}.$EXTENSION_HTML: ambiguous redirect
./include/outputs: line 430: ${OUTPUT_FILE_NAME}.$EXTENSION_HTML: ambiguous redirect
./include/outputs: line 431: ${OUTPUT_FILE_NAME}.$EXTENSION_HTML: ambiguous redirect
./include/outputs: line 432: ${OUTPUT_FILE_NAME}.$EXTENSION_HTML: ambiguous redirect

### Description

Quotes have been added in the prowler file and also in the output file. It seems this has solved the situation and now prowler is running nice.

### License

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Comment by toniblyx** [comment]
Hi @xavi-bean, I use MacOS to develop and test and I don´t see these errors. Can you provide more information on how to replicate them?

**Comment by xavier-sky** [comment]
Sorry maybe had to specify I received this error when using **-M html** output. Apart from this, nothing special: **_./prowler -p role -r region -M html_**

**Comment by toniblyx** [comment]
can you try with latest version of prowler from master or at least 2.7? I can´t reproduce it. Also make sure you have bash-5.1

**Comment by toniblyx** [comment]
And could you please unify both PR to just one? Thanks in advance!

**Comment by xavier-sky** [comment]
I think I have put both here now.
Run this afternoon, the version from master directly. Realized was running Python 2.7, so probably for this reason. If this is the fault, it's worth knowing prowler runs with that Python version only quoting the paths :)
Shell is zsh btw.

**Comment by lazize** [comment]
```shell
$ export MY_VAR="My Value"
$ echo ${MY_VAR}
My Value
$ echo "${MY_VAR}"
My Value
$ echo '${MY_VAR}'
${MY_VAR}
```

**Comment by toniblyx** [comment]
Even if you use zsh Prowler will use Bash. I don't think it is related with Python at all. @xavi-bean see @lazize comment above.

**Comment by xavier-sky** [comment]
Don't ask me how/why but today I've run it without errors and removing the quotes I put yesterday.
The truth is that the errors are there and in that case quoting the file path (in html output option) was the solution in my case 🤷🏻‍♂️.

**Comment by jfagoagas** [comment]
Hi @xavi-bean, we are closing this PR. Please, feel free to reopen it if you can provide us more information about your issue.

Thank you!

**Pull request closed without merging**
