### PR TITLE
fix(dashboard): Add multiple dashboard fixes

### PR DESCRIPTION
**Pull request by pedrooot**
### Context

This pr adds multiple dashboard fixes

### Description

Fixes / improvements:
* Add new filters (Severity / Service / Status)
* Change font-weight for table-overview
* Make provider cards clickable (click to filter by provider)
* Dropdown to show rows on table-overview
* Use global variables in color

### License

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Comment by MrCloudSec** [comment]
Once I click one provider card, how can I unclick it?

**Comment by pedrooot** [comment]
@sergargar if you reload the page all filters will be reset

**Comment by pedrooot** [comment]
@sergargar I was thinking about your question and made some changes, now you can select a card that is selected to disable the filter for the provider

**Review by MrCloudSec — APPROVED** [review]
Loved this!!

**Pull request merged**
