### PR TITLE
feat(aws): Add new AWS Lambda check to check public access via other services

### PR DESCRIPTION
**Pull request by abant07**
Lambda test case not working @jfagoagas

### CODE REVIEW

**Comment by jfagoagas** [comment]
Hi @abant07, we're about to review this PR but I don't get the point of the title and the PR body, can you elaborate it a little bit? Are you trying to fix an issue or just creating two new checks?

**Comment by abant07** [comment]
Hey @jfagoagas 

Sure, so for this PR I was adding a new feature to prowler where it would detect resources behind an internet facing ALB and ELB. I have written the two new checks for EC2 and it was working fine, however, I wrote a check for lambda and it was giving some trouble.

the check for lambda is giving a client token id error when I test it using mock_aws.

Thanks

**Comment by jfagoagas** [comment]
> Hey @jfagoagas
> 
> Sure, so for this PR I was adding a new feature to prowler where it would detect resources behind an internet facing ALB and ELB. I have written the two new checks for EC2 and it was working fine, however, I wrote a check for lambda and it was giving some trouble.
> 
> the check for lambda is giving a client token id error when I test it using mock_aws.
> 
> Thanks

So both are present in this PR right?
1. Review these new checks
2. Fix the issue with the new Lambda check called `awslambda_function_not_directly_publicly_accessible_via_elbv`.

Am I right?

Thanks!

**Comment by abant07** [comment]
Yup you got it.

Thanks

**Comment by jfagoagas** [comment]
@abant07 we need push permissions to your branch in order to fix and improve some parts of the code.

**Comment by abant07** [comment]
Sure, I have just invited you.

Thanks

**Comment by jfagoagas** [comment]
Closed in favor of #3801

**Pull request closed without merging**
