### PR TITLE
New check 7160 Logging is enabled on CloudTrail Trails @kbgoll05

### PR DESCRIPTION
**Pull request by kbgoll05**
Adding a check to verify if logging is enabled on CloudTrail trails.

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Comment by toniblyx** [comment]
Thanks @kbgoll05 but that check already exist as part of `check21` in https://github.com/toniblyx/prowler/blob/master/checks/check21#L51

**Comment by kbgoll05** [comment]
> Thanks @kbgoll05 but that check already exist as part of `check21` in https://github.com/toniblyx/prowler/blob/master/checks/check21#L51

Oh is it! I didn't know that. Thanks for letting me know. Where do I find an updated list of backlog items that I can work on?

**Comment by toniblyx** [comment]
Working on that list I'll make it public asap. I'll let you know

**Comment by toniblyx** [comment]
I´m closing this one, If you want an idea, could you write a check about secrets manager to have rotation enabled? Thanks

**Comment by kbgoll05** [comment]
> I´m closing this one, If you want an idea, could you write a check about secrets manager to have rotation enabled? Thanks

Sure. Thanks for that. I'll work on the secrets manager check.

**Pull request closed without merging**
