### PR TITLE
check28 only look at symmetric keys

### PR DESCRIPTION
**Pull request by michaeldop**
AWS doesn't support the automatic rotation of asymmetric keys

Example of symmetric key details:
```
{
    "key": "",
    "state": "Enabled",
    "man": "CUSTOMER",
    "spec": "SYMMETRIC_DEFAULT"
}
```
Example of asymmetric key details:
```
{
    "key": "",
    "state": "Enabled",
    "man": "CUSTOMER",
    "spec": "ECC_NIST_P256"
}
```

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Comment by michaeldop** [comment]
@toniblyx looks like the implementation changed a bit since I wrote this. I think I am going to have to open another PR to fix

**Comment by toniblyx** [comment]
I'm fixing it now, reverting first and fixing it. Thanks.

**Comment by toniblyx** [comment]
https://github.com/toniblyx/prowler/commit/2883de016e7010cf42adc316642dbd4393cfe198

**Comment by michaeldop** [comment]
just tested that out and works for me. thanks!

**Pull request merged**
