### PR TITLE
fix(cloudtrail): trail.region must be home region

### PR DESCRIPTION
**Pull request by jfagoagas**
### Context

We are storing the CloudTrail Trail region as the `regional_client.region` instead of `HomeRegion` for multi region trails. This is due to the fact that a multi region trail can be checked in whatever region where it is working but we must store the `HomeRegion` as the Trail region since it’s where it was created.

## Description

`trail.region` must have the region where the trail was created.

### License

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Review by pedrooot — DISMISSED** [review]
Good approach! Thanks @jfagoagas

**Comment by jfagoagas** [comment]
Another option should be to leave the service as is and update the checks to use `finding.region = trail.home_region`.

**Comment by MrCloudSec** [comment]
> Another option should be to leave the service as is and update the checks to use `finding.region = trail.home_region`.

I would do this approach, setting the `home_region` as region in all the checks except from the two `cloudtrail_multi_region_enabled*` checks.

**Review by MrCloudSec — APPROVED** [review]
Good catch!

**Pull request merged**
