### PR TITLE
Use batch-update-findings for issue updates

### PR DESCRIPTION
**Pull request by gyrospectre**
By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

Update the way previously raised, now fixed, findings are updated by Prowler. Rather than re-import, which seems to cause problems when using ECS/Fargate, use the `batch-update-findings` action to update the finding.

### CODE REVIEW

**Comment by toniblyx** [comment]
if you look at https://docs.aws.amazon.com/securityhub/latest/partnerguide/partnerguide.pdf:
```
Does the partner update findings by calling the BatchImportFindings operation with the existing
findings' finding ID?
To update a finding, you must overwrite the existing finding by submitting the same finding ID.
The BatchUpdateFindings operation should only be used by customers.
Does the partner update findings using the BatchUpdateFindings API?
If you take action on findings, you can use the BatchUpdateFindings operation to update specific
fields
```

So the error should come from other place. We are testing and releasing soon a template that will allow to use fargate for multiaccount, look at this one as an example https://github.com/cdemko-mwr/prowler-multiaccount/

**Comment by toniblyx** [comment]
I said this already but can you also review this issue comments? Not related? https://github.com/toniblyx/prowler/issues/705

**Comment by toniblyx** [comment]
Can you also make sure you have Prowler integration enabled in both master and child accounts?

**Comment by gyrospectre** [comment]
Per my comments in #711, this is an issue with a single account, not multiaccount - I don't believe this issue is related to #705. Prowler integration is indeed enabled on the account in question. Happy for you to reject this PR if it's not correct and a better fix is on the way?

**Comment by gyrospectre** [comment]
Closing this pull request per concerns above.

**Pull request closed without merging**
