### PR TITLE
Tweaks - AWS Account ID, -V flag

### LINKED ISSUE #204: 2.0-beta - missing AWS account IDs in CSV output
when running prowler with  -c or -g, the checks are run without calling getWhoami, resulting in the ACCOUNT_NUM variable never getting set and an empty account number in the output.

### PR DESCRIPTION
**Pull request by MrSecure**
fixes #204 

restores AWS Account ID in csv output
adds -V flag to report prowler version

### CODE REVIEW

**Review by toniblyx — APPROVED** [review]
Thanks @MrSecure, you are always looking after Prowler, hope you like the 2.0 changes in general and  enjoyed the sticker ;)

**Comment by MrSecure** [comment]
the 2.0 changes are IMPRESSIVE!!    Very excited!

**Comment by toniblyx** [comment]
Thanks, btw, why capital `-V` instead of lower?

**Comment by MrSecure** [comment]
seems to be somewhat normative across lots of the tools I've used ... little "v" is for "verbose",  big "V" is for "VERSION".    So, habit, I guess?

**Comment by toniblyx** [comment]
makes sense, I have seen that in many ways too. Ok, it is fine then. Keep an eye, I'll PR a GDPR beta group of checks in a moment, still work in progress.

**Pull request merged**
