### PR TITLE
Rewrite of check extra73

### PR DESCRIPTION
**Pull request by zfLQ2qx2**
This is my rewrite of check extre73 to address https://github.com/toniblyx/prowler/issues/458 where I listed some places where I thought the logic was short-circuiting incorrectly. I've also added access denied checks to everything which should help address https://github.com/toniblyx/prowler/issues/459 as well.

The number of subprocesses launched by the current version of this check is pretty intensive so I've looked for opportunities to do less of that. Biggest win is if public access is blocked at the account level in which case we can skip iterating the buckets altogether. If we are using prowler to generate an inventory then maybe that isn't what people want, but seems like a huge win day to day.

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Comment by zfLQ2qx2** [comment]
@toniblyx One more PR for Prowler

**Comment by toniblyx** [comment]
This one is much better now, thanks!

**Comment by estemendoza** [comment]
Hi Guys.

I am experiencing a weird issue with this check. It seems that for some reason, the region value is populated with the name of the bucket, instead of the actual region, I tried today with the latest changes on master.

**Comment by toniblyx** [comment]
Thanks @estemendoza, could you please share the output of this check using this command? `bash -x ./prowler -c extra73` also remember to remove/fake sensitive info please. 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by estemendoza** [comment]
Ok, I executed that command and didn't want to paste the entire thing, but I think this piece of output shows that the region is taken correctly:

```
++ /usr/bin/aws s3api get-bucket-location --bucket **** --profile **** --output text
+ BUCKET_LOCATION=eu-west-1
++ echo eu-west-1
```

I was thinking that maybe the problem is when these results are saved as CSV? I forgot to say that the results are saved as CSV

**Pull request merged**
